version: '3'

services:

  web:
     build:
       context: ./docker/code1
       dockerfile: Dockerfile
     image: web_be
     environment:
       - ALLOW_OVERRIDE=true
     ports:
       - "80:80"
     networks:
       - bitfalcon_network
     env_file:
       - setup_env/code1/.env
     container_name: web_be
     links:
       - db
     volumes:
       - ./code1:/var/www/html/code1:rw
       - ./setup_apache/code1/vhost.conf:/etc/apache2/sites-available/000-default.conf:rw
     networks:
       - bitfalcon_network

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./setup_mysql/code1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_DATABASE: mysqldb
    ports:
      - "3307:3306"
    networks:
      - bitfalcon_network
    container_name: dtbase

  phpmyadmin:
    image: phpmyadmin:5.1
    links:
      - db
    ports:
      - 81:80
    networks:
      - bitfalcon_network
    container_name: back
    environment:
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_DATABASE: mysqldb
  api:
     build:
       context: ./docker/code2
       dockerfile: Dockerfile
     image: web_fe
     environment:
       - ALLOW_OVERRIDE=true
     ports:
       - "83:80"
     networks:
       - bitfalcon_network
     container_name: web_fe
     links:
       - web
     volumes:
       - ./code2:/var/www/html/code2:rw
       - ./setup_apache/code2/vhost.conf:/etc/apache2/sites-available/000-default.conf:rw
     networks:
       - bitfalcon_network

networks:
  bitfalcon_network:
    driver: bridge
